### ISSUE TITLE
reduce dependencies

### ISSUE THREAD

**Issue by liamquin** [w3c-ccg/did-wg-charter#1]
i usually advise people to have as few dependencies as they can get away with on other groups, because you need active sign-off from them to publish a Rec. So i'd take WoT and Publishing off as hard formal requirements.

The timeline looks achievable to me depending on how many dissenting voices join the WG :) and overall looks fine as a draft. Thanks for doing this.

**Comment by msporny** [comment]
> So i'd take WoT and Publishing off as hard formal requirements.

Ok, will do.
