### ISSUE TITLE
Out of Scope: Auth, Signing, Cryptography mechanisms

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#14]
Please add "defining any authentication mechanisms,  signing mechanisms or cryptography mechanisms" or what ever wording you see fit to express that these are out of scope

**Comment by kimdhamilton** [comment]
Changed title from "Out of Scope" to "Out of Scope: Auth, Signing, Cryptography mechanisms"

**Comment by dlongley** [comment]
Whatever wording we use should make sure we don't preclude defining extension points for where things like authentication go.

**Comment by nadalin** [comment]
@dlongley Only if there if there is a mechanism referenced that one can use for interop otherwise field is useless

**Comment by kimdhamilton** [comment]
we have to enable mechanisms, but not define them

**Comment by kimdhamilton** [comment]
Addressed in https://github.com/w3c-ccg/did-wg-charter/pull/34

**Comment by nadalin** [comment]
@kimdhamilton This should also say something about the interoperability not just the enabling as enabling may not get us to any interoperability

**Comment by msporny** [comment]
The group discussed this on the 2019-06-17 call and agreed that the PR that was merged reflects the desire of the group to enable mechanisms. The group also discussed adding statements around interoperability as suggested by @nadalin but felt that the current text in the current charter is appropriate. Closing.
