### ISSUE TITLE
Out of Scope: Access Management and Identity Management

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#15]
You have "Solving Identity" on the Web" is out of scope but you have "Concentrate their efforts on the identified use cases with a particular focus on Identity and Access Management. Use cases from other industries may be included if there is significant industry participation." which is focusing on Identity Management and Access Management.

I expect Access Management and Identity Management to be out of scope. 

I also believe that use cases are out of scope as they have not been defined yet

**Comment by kimdhamilton** [comment]
Changing title from "Out of Scope" to "Out of Scope: Access Management and Identity Management"

**Comment by kimdhamilton** [comment]
I originally addressed this in https://github.com/w3c-ccg/did-wg-charter/pull/30, but that change got clobbered in a merge. Re-added in https://github.com/w3c-ccg/did-wg-charter/pull/34

**Comment by msporny** [comment]
We discussed this on the 2019-06-27 call and agreed that the merged PR further clarifies that IAM is out of scope, but the group wants to enable it. Closing.

**Comment by nadalin** [comment]
@msporny you have to explain what "enable" means as the charter needs to be very clear on scope and some people think "enable" means define/implement, I would not accept this being closed w/o clarification

**Comment by msporny** [comment]
> @msporny you have to explain what "enable" means as the charter needs to be very clear on scope and some people think "enable" means define/implement, I would not accept this being closed w/o clarification

@TallTed has further refined what is meant by "enable" in PR #49 and it seems to be aligned with what you were wanting. We'll review and most likely merge this change in the next call.
