### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#17]
"The controller of a DID can cryptographically authenticate themselves (e.g. DID-based website login) ."

This should be removed as authentication out of scope for this WG and I'm not sure that a DID must always provide this feature 

."

**Comment by msporny** [comment]
This was discussed on the 2019-06-27 call, the group agreed that the PR is appropriate. There was confirmation that @nadalin agreed to the change during a separate call. Closing.
