### ISSUE TITLE
Discovery

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#18]
"DIDs provide discovery information for bootstrapping into more secure and privacy preserving communication protocols (e.g. encrypted messaging endpoints). "

I'm not sure what "more secure protocols means" Clarify please as it sound like you are inventing some new security protocols

**Comment by msporny** [comment]
The PR removes the word "more" as requested. The group discussed if this change was adequate on the 2018-06-27 call and agreed that it was. Closing.
