### ISSUE TITLE
Portability 

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#19]
"DIDs provide a path to service agnostic data portability (e.g. switching between Verifiable Credential digital wallet providers). "

There should be no dependency on VC so add another example or remove VC as a example as this leads one to belive this is only about VC

**Comment by kimdhamilton** [comment]
Verifiable Credentials are just listed as an example here, but we should double-check the language to ensure we're not calling out VCs as a dependency

**Comment by nadalin** [comment]
@kimdhamilton Maybe add others and not limit

**Comment by msporny** [comment]
The group discussed this on the 2019-06-27 call and agreed that the PR clarifies that the charter is not limited to being only applicable to Verifiable Credentials. Closing.
