### ISSUE TITLE
DID Resolution

### ISSUE THREAD

**Issue by peacekeeper** [w3c-ccg/did-wg-charter#2]
There seems to be agreement that eventually there should be a separate spec for DID Resolution. An early skeleton document for this exists at https://w3c-ccg.github.io/did-resolution/.

Let's decide whether DID Resolution should be 1. In scope of the DID WG Charter, 2. Listed as an optional deliverable, or 3. Not in scope for now, first incubate it further in the Credentials CG.

**Comment by nadalin** [comment]
@peacekeeper There has to be some mechanisms in scope for interoperability

**Comment by peacekeeper** [comment]
@nadalin do you mean
1. Interoperability between different DID methods (e.g. Sovrin DIDs, BTCR DIDs, etc.)? This is a basic assumption anyway and this is exactly what the spec is about. All DIDs will resolve to the same interoperable document format. No matter what type of DID you use, discovering its public key or agent/hub/etc. endpoint always works the same way.
2. Interoperability with non-DID technologies such as DNS, HTTP, etc.? Several topics here are being discussed. E.g. you can query a DID resolver via an HTTP binding to retrieve a DID document using any standard HTTP library. There's also a draft spec for [discovering a DID from a domain name](https://datatracker.ietf.org/doc/draft-mayrhofer-did-dns/). And there's a proposed (controversial) way to [wrap domain names into DID syntax](https://github.com/uport-project/specs/blob/develop/did-methods/https-did-method.md).

**Comment by nadalin** [comment]
@peacekeeper So point is that there should be documented DID methods such as BTCR that anyone could implement and interoperate upon, so if I pick up the DID document it will list BTCR and I can then look in the normative reference and find the BCTR method and implement that and that would be a sign of a interop if 2 or more can actual use a specified mechanism

**Comment by peacekeeper** [comment]
@nadalin Yes absolutely. The DID Resolution spec, in conjunction with a certain DID method spec (such as btcr), will enable this. Different implementations of a DID resolver will produce the same result for a given input DID. In the case of btcr, there are already at least 3 independent implementations out there (although in practice they are not completely interoperable yet).

**Comment by nadalin** [comment]
@peacekeeper So I'm glad you agree that there will be defined DID methods in the specification and there will interop on those methods, so the charter just needs to be clarified to show that

**Comment by peacekeeper** [comment]
I don't think the DID spec will itself define or even mention concrete DID methods such as "btcr", but the DID spec will define the DID method mechanism as well as requirements for DID method specs, so that methods can then be defined in a way that enables interoperable implementations.

**Comment by kimdhamilton** [comment]
I think this is ok to close 
cc: @msporny @peacekeeper

**Comment by peacekeeper** [comment]
@kimdhamilton I agree to close it for now.
