### ISSUE TITLE
Replace "owner" with "controller"

### ISSUE THREAD

**Issue by jandrieu** [w3c-ccg/did-wg-charter#3]
As mentioned elsewhere, "owner" is a problematic term. "Controller" would be more rigorous.

**Comment by msporny** [comment]
Done.

**Comment by ChristopherA** [comment]
+1 to c/own/control/

It is clear to me looking at various long term legal issues that GDPR is on side the side of identity control from a basis of human rights , whereas US/Google/Facebook wants identity as property.
