### ISSUE TITLE
Machines don't own things

### ISSUE THREAD

**Issue by jandrieu** [w3c-ccg/did-wg-charter#4]
The opening bullet list says:
> DIDs are owned by individuals, organizations, and machines, not leased from an authority (e.g. DNS Registrars).

Except, machines don't own things.

**Comment by msporny** [comment]
Fixed in https://github.com/w3c-ccg/did-wg-charter/commit/4cb6dca57ab91ebb5a53ef004c950044ee0204bb by changing "owned" to "controlled".
