### ISSUE TITLE
Web Support

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#42]
I don't understand why there is no requirement for web support (browser), how are these identifiers going to be used via the web?

**Comment by msporny** [comment]
The group is scoping the DID WG Charter to something that they feel is achievable given the shorter WG timeframes at W3C these days.

Therefore, browser APIs are marked as out of scope for this charter. 

There may be work performed in the future with respect to browser APIs. At present, organizations are using DIDs outside of the browser environment as well as within the browser environment without the need for explicit support by browser APIs (and thus browser API support isn't a requirement).

Suggestion is to close this issue as the DID WG Charter is clear wrt. Browser APIs being out of scope.

**Comment by jandrieu** [comment]
DIDs are identifiers with clear resolution and dereferencing semantics. Browser use (within the address bar or as the target for an anchor tag) is the same as for any new URL scheme. It may be relevant to explain that more clearly.

However, for in-DOM use, e.g., by JavaScript on a web page, I agree with Manu that such an API is out of scope.

Is there any appropriate place to state something along the lines of "As a URL, any browser can support user entry in the address bar and link semantics in anchor tags by implementing the appropriate resolution and dereferencing mechanisms in supported DID methods."

**Comment by nadalin** [comment]
@msporny I don't agree with the resolution since the charter is unclear, needs to call it out in the out of scope section

**Comment by msporny** [comment]
@nadalin The charter already includes Browser APIs as out of scope, it already does what you are requesting.

**Comment by msporny** [comment]
@nadalin - additionally, the charter explains the following (which should be sufficient for questions related to how browsers are expected to support DIDs):

> The pattern for the DID spec is the URI spec (RFC 3986). That spec defines the generic syntax for URIs, and all URI schemes are separate specs (in fact, the DID spec is one of those specs, i.e., a fully RFC 3986 conformant URI scheme). The goal of the DID spec is to do exactly the same for DIDs, i.e., for this WG to define the generic DID spec, and then for others to define DID method specs.

**Comment by msporny** [comment]
The group discussed this on 2019-07-02 and agreed with the comments in https://github.com/w3c-ccg/did-wg-charter/issues/42#issuecomment-507799307 and https://github.com/w3c-ccg/did-wg-charter/issues/42#issuecomment-507799935. Closing.
