### ISSUE TITLE
Methods vs. Operations

### ISSUE THREAD

**Issue by nadalin** [w3c-ccg/did-wg-charter#43]
So there is an issue about interop and defining a method or multiple methods, another option would be to define the operations, that each method must implement and then interop on the operations that each method must support

**Comment by msporny** [comment]
Different DID Methods may implement DID operations differently and this is largely a protocol issue, which you will note is out of scope in the charter.

PR #51 sets clear expectations wrt. interop.

Suggest we close the issue with no changes to the charter.

**Comment by jandrieu** [comment]
Agreed. #51 is a good adjustment to make sure the group tackles this problem adequately.

+1 to closing.

**Comment by nadalin** [comment]
@msporny I don't agree with resolution and closing

**Comment by jandrieu** [comment]
Propose a resolution, then, @nadalin 

The spec already defines which operations a method MUST support. 

What would you like to see changed and what would you like it changed to?

**Comment by nadalin** [comment]
@jandrieu Then that should be the proposed interoperability point, and defining operations is not defining a protocol. Propose to add a section on interperability and state that interop will happen on the operations level independent of the method

**Comment by jandrieu** [comment]
You misunderstand, @nadalin. The operations that MUST be supported is not the same as how those operations are implemented, which is a protocol level spec.  And all of this is spec work that merely needs to be identified as work for the working group. The charter is NOT the place to specify the operations.

Let me ask more clearly, what text, in the charter, would you like changed and what would you like it changed to?

**Comment by msporny** [comment]
The group discussed this on 2019-07-02 and agrees that the goal of the DID WG is to define interop at the DID syntax, DID Document data model, and DID Method specification requirements level and not to define a protocol, which would be required to achieve operation-level interop independent of the method. The DID WG Charter already specifies protocol as out of scope for the WG.

**Comment by nadalin** [comment]
@msporny The operation is independent from the protocol, as each protocol can implement the operation differently.

**Comment by nadalin** [comment]
@msporny I don't agree with closing this with the rational given here
