### ISSUE TITLE
add link to SSI principles

### ISSUE THREAD

**Issue by brentzundel** [w3c-ccg/did-wg-charter#46]
The "Self-Sovereign Principles" document has shaped much of the thought and direction of decentralized identifiers, so there should be a reference to it in the charter.

**Comment by ChristopherA** [comment]
Version 1.0 of the principles is at https://github.com/WebOfTrustInfo/self-sovereign-identity/blob/master/self-sovereign-identity-principles.md — there is some discussion in the issues in that repository toward iterating to a 1.1 or 2.0 version of the principles.
