### ISSUE TITLE
DID charter does not include defining DID (scheme) itself

### ISSUE THREAD

**Issue by burnburn** [w3c-ccg/did-wg-charter#5]
The charter only lists the specification of DID documents, but not the DID url itself (the DID scheme).  This is a critical omission.

**Comment by kimdhamilton** [comment]
We may also need to clarify what's out of scope, e.g.:
- DID auth
- Resolver

**Comment by nadalin** [comment]
@kimdhamilton Agree on DID Auth, but leaving a defined resolver out not sure how one would show interop, I agree that working on a resolver is out of scope

**Comment by talltree** [comment]
I too noticed that the charter did not explicitly say "Define the DID URI Scheme". I guessed that the authors assumed it would be part of defining the data model. But for this spec, the definition of the DID scheme is central enough that it should be called out explicitly.

**Comment by kimdhamilton** [comment]
This is an omission; seems non-controversial to make this change

**Comment by nadalin** [comment]
@kimdhamilton Only if this limits this to only a VC and I would have to understand why this has to be a URI Scheme

**Comment by kimdhamilton** [comment]
Brought this up to date: https://github.com/w3c-ccg/did-wg-charter/pull/6/files
