### ISSUE TITLE
Test suite should be listed in deliverables

### ISSUE THREAD

**Issue by jandrieu** [w3c-ccg/did-wg-charter#55]
Section 1.2 Success Criteria specifies a test suite, but that is not listed as a deliverable in Section 1. Scope.

IMO, this is editorial since, clearly, a test suite is meant to be a deliverable of the working group.

**Comment by msporny** [comment]
Yep, charter already identified test suite as in scope. The change is editorial.

Fixed in 603f07b969d9a5e8071df52f9652a887f0e8c2b7.
